### ISSUE TITLE
The provided google drive links dont seem to be working...

### ISSUE THREAD

**Issue by philiparxist** [getalp/UFSAC#10]

**Comment by loic-vial** [comment]
Hi, thank you for opening this issue. I'm working on it right now, I'll notify you when the links are back :)

**Comment by liyucheng09** [comment]
Thanks for your efforts. Waiting for updates as well!

**Comment by loic-vial** [comment]
Hi ! I'm so sorry for the delay but the new link for the latest version of UFSAC (2.1) is finally ready : 
--> [https://drive.google.com/file/d/1kwBMIDBTf6heRno9bdLvF-DahSLHIZyV](https://drive.google.com/file/d/1kwBMIDBTf6heRno9bdLvF-DahSLHIZyV)

I'm gonna update the README with the new link asap.

@philiparxist and @liyucheng09 can you confirm that it's ok for you ? Thank you !

**Comment by philiparxist** [comment]
@loic-vial thank you for updating the link. this works for me.
