### ISSUE TITLE
Agreement with NLTK WordNet

### ISSUE THREAD

**Issue by etienne-v** [getalp/UFSAC#2]
Hi,

Thank you very much for your work!

I have a question with regard to the WNGT dataset keys and how they correspond to the keys from the NLTK WordNet corpus.  The WN version from NLTK is 3.0:
```
import nltk
nltk.download('wordnet')
from nltk.corpus import wordnet as wn
print(wn.get_version())
3.0
```
According to the `ufsac-public-2.1/wngt.xml ` file, the entry
`<sentence wn30_key="drive%1:04:03::;driving%1:04:03::" >`
for example, has associated with it the definition "hitting a golf_ball off of a tee with a driver".  
 However, using one of these keys to obtain the synset and associated definition from the NLTK WordNet corpus gives:
```
print(wn.synset_from_sense_key("drive%1:04:03::").definition())
a series of actions advancing a principle or tending toward a particular end
```
It seems that some of the keys from NLTK's WordNet and the wngt.xml don't point to the same gloss definition even though both WordNet versions are 3.0.  Any thoughts?

**Comment by loic-vial** [comment]
Hi,

So I checked 3 different sources:

- The official WordNet 3.0 database (http://wordnetcode.princeton.edu/3.0/WordNet-3.0.tar.gz)
---> Open the file "dict/index.sense" and search for the sense key "drive%1:04:03::" (line 55430)
---> It gives the synset ID which is "00572489"
---> Open the file "dict/data.noun" and search for the line beginning with "00572489" (line 2888)

- The official WordNet Gloss Corpus (http://wordnetcode.princeton.edu/glosstag-files/WordNet-3.0-glosstag.tar.gz)
---> Open the file "merged/noun.xml" and search for the sense key "drive%1:04:03::" (line 117193)

- The online version of WordNet (which is version 3.1) (http://wordnetweb.princeton.edu/perl/webwn)
---> Search for "drive" and display sense key

All three sources give the same definition "hitting a golf ball off of a tee with a driver" :)

I hope it helped you !

**Comment by etienne-v** [comment]
Thank you @coylz, it does help!  The problem is then with the WordNet corpus of NLTK.

**Comment by etienne-v** [comment]
@coylz Could you perhaps assist with interpreting the WordNet database files themselves?  From your explanation above and by looking at the files, I'm able to find all the senses related to a word, as well as the gloss definition of a word.  Is it possible to obtain, for a given sense, its hypernym, hyponyms, and co-hyponyms?  As well as the antonym for a word.  I couldn't find a readme file or manual that explains how to interpret and decipher the different symbols in the database files (in the dict/ folder).  Do you perhaps know how to obtain these relations from the WordNet files themselves?  Any help will be appreciated.... 
Many Thanks!

**Comment by loic-vial** [comment]
Hi ! I'm sorry but I'm really not an expert in reading the database files, I don't know how to find the relationships of a sense. What I suggest is to take a look at JWI [http://projects.csail.mit.edu/jwi/](http://projects.csail.mit.edu/jwi/), it's the Java WordNet Interface library that we use internally.
