### ISSUE TITLE
No license or copyright statement

### ISSUE THREAD

**Issue by goodmami** [getalp/UFSAC#7]
The Java code and scripts in this repository have no license or even a copyright statement that I could find. Can you please clarify the terms of reuse with a license?

**Comment by loic-vial** [comment]
Hi, thank you for having informed us !
I added a simple MIT license to the project :)

**Comment by goodmami** [comment]
Great, thanks!

Also note that this is an issue for [disambiguate](https://github.com/getalp/disambiguate).
